In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
X, y = load_digits(return_X_y= True)

In [3]:
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [4]:
X_train

array([[ 0.        , -0.33501649, -0.46382335, ...,  1.05712311,
         0.47246651, -0.19600752],
       [ 0.        , -0.33501649,  0.79840364, ..., -0.63808502,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       ...,
       [ 0.        , -0.33501649,  0.79840364, ...,  1.56568555,
        -0.01660165, -0.19600752],
       [ 0.        , -0.33501649, -0.88456568, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.88456568, ..., -0.97712664,
        -0.5056698 , -0.19600752]])

In [5]:
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

In [6]:
X_train

tensor([[ 0.0000, -0.3350, -0.4638,  ...,  1.0571,  0.4725, -0.1960],
        [ 0.0000, -0.3350,  0.7984,  ..., -0.6381, -0.5057, -0.1960],
        [ 0.0000, -0.3350, -1.0949,  ..., -0.1295, -0.5057, -0.1960],
        ...,
        [ 0.0000, -0.3350,  0.7984,  ...,  1.5657, -0.0166, -0.1960],
        [ 0.0000, -0.3350, -0.8846,  ..., -1.1466, -0.5057, -0.1960],
        [ 0.0000, -0.3350, -0.8846,  ..., -0.9771, -0.5057, -0.1960]])

In [16]:
class MLP(nn.Module):
  def __init__(self):
    super().__init__()
    self.net = nn.Sequential(
        nn.Linear(64, 128),
        nn.ReLU(),
        nn.Linear(128, 64),
        nn.ReLU(),
        nn.Linear(64, 10)
    )

  def forward(self, x):
      return self.net(x)

In [17]:
MLP

__main__.MLP

In [18]:
model = MLP()

In [19]:
loss_fn = nn.CrossEntropyLoss()

In [20]:
loss_fn

CrossEntropyLoss()

In [21]:
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [22]:
for epoch in range(50):
  model.train()
  outputs = model(X_train)
  loss = loss_fn(outputs, y_train)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [23]:
model.eval()
with torch.no_grad():
  preds = model(X_test).argmax(dim = 1)
  acc = accuracy_score(y_test, preds)
  print("test Accuracy", acc)

test Accuracy 0.9111111111111111


In [25]:
import numpy as np

new_data_raw = np.random.rand(64).reshape(1, -1)

In [30]:
new_data_raw

array([[0.96568223, 0.59314014, 0.1093486 , 0.83520381, 0.03556793,
        0.57645489, 0.9389627 , 0.92360867, 0.26990946, 0.59416095,
        0.00174164, 0.22583704, 0.26276272, 0.29481759, 0.4189335 ,
        0.63546149, 0.81071119, 0.2054915 , 0.40249166, 0.82881903,
        0.12241555, 0.91720561, 0.66747974, 0.11158156, 0.19188545,
        0.66074882, 0.73826544, 0.8472861 , 0.45376178, 0.76215203,
        0.32801422, 0.05469143, 0.99104756, 0.01963106, 0.58488734,
        0.61924846, 0.94840374, 0.52233322, 0.46232771, 0.34071361,
        0.06725443, 0.62113432, 0.30618265, 0.37837995, 0.85474795,
        0.93468135, 0.7178652 , 0.4661266 , 0.86304477, 0.72973116,
        0.66855265, 0.25455198, 0.52572193, 0.41435806, 0.18894931,
        0.77920876, 0.25073987, 0.1705468 , 0.88185311, 0.78725811,
        0.1298611 , 0.11468926, 0.20733364, 0.59975894]])

In [26]:
scaler = StandardScaler()

In [27]:
scaler.fit(X)

StandardScaler()

In [28]:
new_data_scaled = scaler.transform(new_data_raw)

In [29]:
new_data_scaled

array([[0.96568223, 0.59314014, 0.1093486 , 0.83520381, 0.03556793,
        0.57645489, 0.9389627 , 0.92360867, 0.26990946, 0.59416095,
        0.00174164, 0.22583704, 0.26276272, 0.29481759, 0.4189335 ,
        0.63546149, 0.81071119, 0.2054915 , 0.40249166, 0.82881903,
        0.12241555, 0.91720561, 0.66747974, 0.11158156, 0.19188545,
        0.66074882, 0.73826544, 0.8472861 , 0.45376178, 0.76215203,
        0.32801422, 0.05469143, 0.99104756, 0.01963106, 0.58488734,
        0.61924846, 0.94840374, 0.52233322, 0.46232771, 0.34071361,
        0.06725443, 0.62113432, 0.30618265, 0.37837995, 0.85474795,
        0.93468135, 0.7178652 , 0.4661266 , 0.86304477, 0.72973116,
        0.66855265, 0.25455198, 0.52572193, 0.41435806, 0.18894931,
        0.77920876, 0.25073987, 0.1705468 , 0.88185311, 0.78725811,
        0.1298611 , 0.11468926, 0.20733364, 0.59975894]])

In [31]:
new_tensor = torch.tensor(new_data_scaled,dtype = torch.float32)

In [32]:
new_tensor

tensor([[0.9657, 0.5931, 0.1093, 0.8352, 0.0356, 0.5765, 0.9390, 0.9236, 0.2699,
         0.5942, 0.0017, 0.2258, 0.2628, 0.2948, 0.4189, 0.6355, 0.8107, 0.2055,
         0.4025, 0.8288, 0.1224, 0.9172, 0.6675, 0.1116, 0.1919, 0.6607, 0.7383,
         0.8473, 0.4538, 0.7622, 0.3280, 0.0547, 0.9910, 0.0196, 0.5849, 0.6192,
         0.9484, 0.5223, 0.4623, 0.3407, 0.0673, 0.6211, 0.3062, 0.3784, 0.8547,
         0.9347, 0.7179, 0.4661, 0.8630, 0.7297, 0.6686, 0.2546, 0.5257, 0.4144,
         0.1889, 0.7792, 0.2507, 0.1705, 0.8819, 0.7873, 0.1299, 0.1147, 0.2073,
         0.5998]])

In [33]:
model.eval()
with torch.no_grad():
  output = model(new_tensor)
  predicted_class = output.argmax(dim=1).item()
  print("Predicted Class:", predicted_class)

Predicted Class: 5
